// generated by Fast Light User Interface Designer (fluid) version 1.0304

#ifndef gui_h
#define gui_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Button.H>
#include <FL/Fl_Return_Button.H>


class GUI {
public:
	GUI();
  Fl_Double_Window *uiw;
private:
  inline void cb_Button1_i(Fl_Button*, void*);
  static void cb_Button1(Fl_Button*, void*);
  inline void cb_Button2_i(Fl_Button*, void*);
  static void cb_Button2(Fl_Button*, void*);
  inline void cb_Button3_i(Fl_Button*, void*);
  static void cb_Button3(Fl_Button*, void*);
  inline void cb_Button4_i(Fl_Button*, void*);
  static void cb_Button4(Fl_Button*, void*);
  inline void cb_Button5_i(Fl_Button*, void*);
  static void cb_Button5(Fl_Button*, void*);
  inline void cb_Button6_i(Fl_Button*, void*);
  static void cb_Button6(Fl_Button*, void*);
  inline void cb_Button7_i(Fl_Button*, void*);
  static void cb_Button7(Fl_Button*, void*);
  inline void cb_Button8_i(Fl_Button*, void*);
  static void cb_Button8(Fl_Button*, void*);
  inline void cb_Button9_i(Fl_Button*, void*);
  static void cb_Button9(Fl_Button*, void*);
public:
  void show();
  void Button1_cb();
  void Button2_cb();
  void Button3_cb();
  void Button4_cb();
  void Button5_cb();
  void Button6_cb();
  void Button7_cb();
  void Button8_cb();
  void Button9_cb();





};
#endif
