// generated by Fast Light User Interface Designer (fluid) version 1.0304

#include "gui.h"

void GUI::cb_Button1_i(Fl_Button*, void*) {
    Button1_cb();
}
void GUI::cb_Button1(Fl_Button* o, void* v) {
  ((GUI*)(o->parent()->user_data()))->cb_Button1_i(o,v);
}

void GUI::cb_Button2_i(Fl_Button*, void*) {
    Button2_cb();
}
void GUI::cb_Button2(Fl_Button* o, void* v) {
    ((GUI*)(o->parent()->user_data()))->cb_Button2_i(o, v);
}

void GUI::cb_Button3_i(Fl_Button*, void*) {
    Button3_cb();
}
void GUI::cb_Button3(Fl_Button* o, void* v) {
    ((GUI*)(o->parent()->user_data()))->cb_Button3_i(o, v);
}

void GUI::cb_Button4_i(Fl_Button*, void*) {
    Button4_cb();
}
void GUI::cb_Button4(Fl_Button* o, void* v) {
    ((GUI*)(o->parent()->user_data()))->cb_Button4_i(o, v);
}

void GUI::cb_Button5_i(Fl_Button*, void*) {
    Button5_cb();
}
void GUI::cb_Button5(Fl_Button* o, void* v) {
    ((GUI*)(o->parent()->user_data()))->cb_Button5_i(o, v);
}

void GUI::cb_Button6_i(Fl_Button*, void*) {
    Button6_cb();
}
void GUI::cb_Button6(Fl_Button* o, void* v) {
    ((GUI*)(o->parent()->user_data()))->cb_Button6_i(o, v);
}

void GUI::cb_Button7_i(Fl_Button*, void*) {
    Button7_cb();
}
void GUI::cb_Button7(Fl_Button* o, void* v) {
    ((GUI*)(o->parent()->user_data()))->cb_Button7_i(o, v);
}

void GUI::cb_Button8_i(Fl_Button*, void*) {
    Button8_cb();
}
void GUI::cb_Button8(Fl_Button* o, void* v) {
    ((GUI*)(o->parent()->user_data()))->cb_Button8_i(o, v);
}

void GUI::cb_Button9_i(Fl_Button*, void*) {
    Button9_cb();
}
void GUI::cb_Button9(Fl_Button* o, void* v) {
    ((GUI*)(o->parent()->user_data()))->cb_Button9_i(o, v);
}



#include "scene.h"


GUI::GUI() {
  { uiw = new Fl_Double_Window(400, 197, "GUI");
    uiw->user_data((void*)(this));
    { 
        Fl_Button* o = new Fl_Button(15, 15, 80, 30, "Button 1");
        o->callback((Fl_Callback*)cb_Button1);
    } 
    {
        Fl_Button* o = new Fl_Button(15, 45, 80, 30, "Button 2");
        o->callback((Fl_Callback*)cb_Button2);
    }
    {
        Fl_Button* o = new Fl_Button(15, 75, 80, 30, "Button 3");
        o->callback((Fl_Callback*)cb_Button3);
    }
    {
        Fl_Button* o = new Fl_Button(15, 105, 80, 30, "Button 4");
        o->callback((Fl_Callback*)cb_Button4);
    }
    {
        Fl_Button* o = new Fl_Button(15, 135, 80, 30, "Button 5");
        o->callback((Fl_Callback*)cb_Button5);
    }
    {
        Fl_Button* o = new Fl_Button(15, 165, 80, 30, "Button 6");
        o->callback((Fl_Callback*)cb_Button6);
    }
    {
        Fl_Button* o = new Fl_Button(100, 15, 80, 30, "Button 7");
        o->callback((Fl_Callback*)cb_Button7);
    }
    {
        Fl_Button* o = new Fl_Button(100, 45, 80, 30, "Button 8");
        o->callback((Fl_Callback*)cb_Button8);
    }
    {
        Fl_Button* o = new Fl_Button(100, 75, 80, 30, "Button 9");
        o->callback((Fl_Callback*)cb_Button9);
    }
    
    uiw->end();
  } // Fl_Double_Window* uiw
}

int main(int argc, char **argv) {
  scene = new Scene;
  return Fl::run();
}

void GUI::show() {
  uiw->show();
}

void GUI::Button1_cb() {
  scene->Button1();
}

void GUI::Button2_cb() {
  scene->Button2();
}

void GUI::Button3_cb() {
    scene->Button3();
}

void GUI::Button4_cb() {
    scene->Button4();
}

void GUI::Button5_cb() {
    scene->Button5();
}

void GUI::Button6_cb() {
    scene->Button6();
}

void GUI::Button7_cb() {
    scene->Button7();
}

void GUI::Button8_cb() {
    scene->Button8();
}

void GUI::Button9_cb() {
    scene->Button9();
}



